---
- name: deploy redis container
  hosts: cpx11n0
  become: true
  vars:
    redis_version: "8.0.1"
    redis_container_name: "redis"
    ansible_python_interpreter: /usr/bin/python3.9
  vars_files:
    - ../../secrets.yml
  tasks:
    - name: ensure docker service is running
      ansible.builtin.systemd:
        name: docker
        enabled: true
        state: started
    - name: pull redis image
      community.docker.docker_image:
        name: "redis"
        tag: "{{ redis_version }}"
        source: pull
    - name: set redis password in .bashrc
      ansible.builtin.lineinfile:
        path: /home/cmj/.bashrc
        line: 'export REDIS_PASS="{{ redis_pass }}"'
        create: yes
        owner: cmj
        group: cmj
        mode: '0644'
    - name: create and run redis container
      community.docker.docker_container:
        name: "{{ redis_container_name }}"
        image: "redis:{{ redis_version }}"
        restart_policy: unless-stopped
        state: started
        published_ports:
          - "6379:6379"
        command: [ "redis-server", "--requirepass", "{{ redis_pass }}" ]
