- name: reboot server
  hosts: c0n3
  vars:
    ansible_python_interpreter: /usr/bin/python3.9
  become: true
  tasks:
    - name: reboot system
      ansible.builtin.reboot:
        reboot_timeout: 180

    - name: ping machine
      ansible.builtin.ping:

