---
- name: install docker
  hosts: all
  become: yes
  tasks:
    - name: install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg2
          - software-properties-common
    - name: add docker gpg key
      get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/trusted.gpg.d/docker.asc
        mode: 0644
        force: true
    - name: add docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian bullseye stable
        state: present
    - name: install engine
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
    - name: add user to docker group
      user:
        name: cmj
        groups: docker
        append: yes
    - name: start docker service
      service:
        name: docker
        state: started
