---
- name: install required packages
  hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3.9
  tasks:
    - name: ensure epel repo is enabled
      ansible.builtin.dnf:
        name: epel-release
        state: present

    - name: install fail2ban
      ansible.builtin.dnf:
        name: fail2ban
        state: present

    - name: copy jail.conf to jail.local
      ansible.builtin.copy:
        src: /etc/fail2ban/jail.conf
        dest: /etc/fail2ban/jail.local
        remote_src: yes
        force: no

    - name: configure fail2ban sshd jail
      ansible.builtin.blockinfile:
        path: /etc/fail2ban/jail.local
        marker: "# {mark} ANSIBLE MANAGED SSHD JAIL"
        block: |
          [sshd]
          enabled = true
          port    = ssh
          filter  = sshd
          logpath = /var/log/secure
          backend = systemd
          maxretry = 3
          findtime = 10m
          bantime = 12h

    - name: restart fail2ban
      ansible.builtin.service:
        name: fail2ban
        state: restarted
