---
- name: install base packages
  hosts: all
  become: yes
  tasks:
    - name: install packages
      ansible.builtin.dnf:
        name:
          - dnf-utils
          - dnf-plugins-core
          - curl
          - vim-enhanced
        state: present
